site_name: Projet SportLudique-Site de Tours
site_description: Documentation technique de l'infrastructure du site Tours

theme:
  name: readthedocs
  language: fr
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Accueil: index.md
  - Infrastructure:
     - Configuration de SSH sur un switch 9200L: infra/ssh-switch-9200L.md
  - Annexes:
      - Commandes utiles: annexes/memo.md
      - Matériel & Connectique: annexes/materiel.md
