site_name: Projet SportLudique-Site de Tours
site_description: Documentation technique de l'infrastructure du site Tours

theme:
  name: readthedocs
  language: fr
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight

